// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yaqeen.Infrastructure.Data.Context;

#nullable disable

namespace Yaqeen.Infrastructure.Migrations
{
    [DbContext(typeof(YaqeenDbContext))]
    [Migration("20260825125508_SeedYaqeenData")]
    partial class SeedYaqeenData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yaqeen.Domain.Entities.Citizen", b =>
                {
                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NationalId");

                    b.ToTable("Citizens");

                    b.HasData(
                        new
                        {
                            NationalId = "1234567890",
                            DateOfBirth = new DateOnly(2003, 3, 3),
                            FullName = "Abdulmajeed Mohammed Alhasani",
                            Gender = "Male",
                            Nationality = "Saudi"
                        },
                        new
                        {
                            NationalId = "1028339274",
                            DateOfBirth = new DateOnly(1990, 11, 15),
                            FullName = "Alhasan Mustafa Alharbi",
                            Gender = "Male",
                            Nationality = "Saudi"
                        },
                        new
                        {
                            NationalId = "1920009789",
                            DateOfBirth = new DateOnly(2005, 2, 28),
                            FullName = "Hamad Ahmed Al Sabah",
                            Gender = "Male",
                            Nationality = "Saudi"
                        });
                });

            modelBuilder.Entity("Yaqeen.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SequenceNumber"));

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("OwnerNationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateLetters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SequenceNumber");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            SequenceNumber = 1,
                            ChassisNumber = "XYZ1234567890",
                            Color = "Black",
                            Make = "Toyota",
                            Model = "Crown Sedan",
                            ModelYear = 2023,
                            OwnerNationalId = "1234567890",
                            PlateLetters = "MJD",
                            PlateNumber = "1303"
                        },
                        new
                        {
                            SequenceNumber = 2,
                            ChassisNumber = "XYZ0987654321",
                            Color = "Blue",
                            Make = "Haval",
                            Model = "V7",
                            ModelYear = 2019,
                            OwnerNationalId = "1028339274",
                            PlateLetters = "DEF",
                            PlateNumber = "5678"
                        },
                        new
                        {
                            SequenceNumber = 3,
                            ChassisNumber = "XYZ5678901234",
                            Color = "Black",
                            Make = "Ford",
                            Model = "Mustang",
                            ModelYear = 2020,
                            OwnerNationalId = "1920009789",
                            PlateLetters = "AAI",
                            PlateNumber = "9012"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
