// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yaqeen.Infrastructure.Data.Context;

#nullable disable

namespace Yaqeen.Infrastructure.Migrations
{
    [DbContext(typeof(YaqeenDbContext))]
    [Migration("20260828130620_AddAddressToCitizen")]
    partial class AddAddressToCitizen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yaqeen.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine = "Riyadh",
                            CitizenId = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine = "Jeddah",
                            CitizenId = "1028339274"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine = "Abha",
                            CitizenId = "1920009789"
                        });
                });

            modelBuilder.Entity("Yaqeen.Domain.Entities.Citizen", b =>
                {
                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NationalId");

                    b.ToTable("Citizens");

                    b.HasData(
                        new
                        {
                            NationalId = "1234567890",
                            DateOfBirth = new DateOnly(2003, 3, 3),
                            FullName = "Abdulmajeed Mohammed Alhasani",
                            Gender = "Male",
                            Nationality = "Saudi"
                        },
                        new
                        {
                            NationalId = "1028339274",
                            DateOfBirth = new DateOnly(1990, 11, 15),
                            FullName = "Alhasan Mustafa Alharbi",
                            Gender = "Male",
                            Nationality = "Saudi"
                        },
                        new
                        {
                            NationalId = "1920009789",
                            DateOfBirth = new DateOnly(2005, 2, 28),
                            FullName = "Hamad Ahmed Al Sabah",
                            Gender = "Male",
                            Nationality = "Saudi"
                        });
                });

            modelBuilder.Entity("Yaqeen.Domain.Entities.Make", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Makes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Haval"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ford"
                        });
                });

            modelBuilder.Entity("Yaqeen.Domain.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MakeId = 1,
                            Name = "Crown Sedan"
                        },
                        new
                        {
                            Id = 2,
                            MakeId = 2,
                            Name = "V7"
                        },
                        new
                        {
                            Id = 3,
                            MakeId = 3,
                            Name = "Mustang"
                        });
                });

            modelBuilder.Entity("Yaqeen.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SequenceNumber"));

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("OwnerNationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateLetters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("MakeId");

                    b.HasIndex("ModelId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            SequenceNumber = 1,
                            ChassisNumber = "XYZ1234567890",
                            Color = "Black",
                            MakeId = 1,
                            ModelId = 1,
                            ModelYear = 2023,
                            OwnerNationalId = "1234567890",
                            PlateLetters = "MJD",
                            PlateNumber = "1303"
                        },
                        new
                        {
                            SequenceNumber = 2,
                            ChassisNumber = "XYZ0987654321",
                            Color = "Blue",
                            MakeId = 2,
                            ModelId = 2,
                            ModelYear = 2019,
                            OwnerNationalId = "1028339274",
                            PlateLetters = "DEF",
                            PlateNumber = "5678"
                        },
                        new
                        {
                            SequenceNumber = 3,
                            ChassisNumber = "XYZ5678901234",
                            Color = "Black",
                            MakeId = 3,
                            ModelId = 3,
                            ModelYear = 2020,
                            OwnerNationalId = "1920009789",
                            PlateLetters = "AAI",
                            PlateNumber = "9012"
                        });
                });

            modelBuilder.Entity("Yaqeen.Domain.Entities.Address", b =>
                {
                    b.HasOne("Yaqeen.Domain.Entities.Citizen", "Citizen")
                        .WithMany("Addresses")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("Yaqeen.Domain.Entities.Model", b =>
                {
                    b.HasOne("Yaqeen.Domain.Entities.Make", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("Yaqeen.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("Yaqeen.Domain.Entities.Make", "Make")
                        .WithMany("Vehicles")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yaqeen.Domain.Entities.Model", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Make");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Yaqeen.Domain.Entities.Citizen", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Yaqeen.Domain.Entities.Make", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Yaqeen.Domain.Entities.Model", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
